# 项目相关配置
chang:
  # 名称
  name: Chang
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2019
  # 演示开关
  demoEnabled: true
  # 文件路径
  profile: D:/profile/
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 80
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
